language: node_js
node_js: node
cache:
  directories:
    - node_modules
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: MUK4t78I3SPSMjVs0eopjLXooKxvI3nJo3+TCF6sGaoGvAXv0dAj9BKoT1zFOEl1K/YygE+nbH+36kRjDpnownqC96KKtOHmu1liGrwuclbCFeEEnldiOeukp2BIgd81YSp9yd/FjK/E5mcNHGeonOCfUlQtRpsQ20V06puPFdvzt2Ogw0mm86q53HCKrnhXf3/k+hNotCjowiPz6NcUUcrk/axvMkdJ/95GSg459/iyk31ptsBmPZs4PixbDiGJZlsbKr6is8TN2K+S83SKBi5pyZxHbK37smbZ+LWWqY433mfV0Nmi7fBlmd31aanmfPjcBu9x20sO2cZ8O1i2qe1G8T6yhwpVkR8LZVWBXVL1UW7ZugAZEOMn0PDBR3gsdC7gOJfagArLSpSEYo4CVEBJCBweJeGaQGonvT8XTrSRMy1/uGlZK9L8i4i3OwWuKHCQ7zqamnJ+IWYEvY4yvoRDjL2FXThhpVQH8Od3GSa+mX6h8iHh/WgWC+fvTC/S1ElqxJv02eBE0F9hQ/CKlhIheYooZeXXecDym66rBJ/DGkfJKMHZp5BFqI1RamKDMOz8+81CQgEvbF4/aVJDGIkXGdE2U7wUYb8wREB1tziwhX3EpH51iEf15h/b1TEgv7c3VEGJdBRqd3vf2ky2+UiU/orDdKL9NyS5fSZXjSM=
  app: lit-forest-52364
  on:
    repo: namninja/react-trello-testing
