language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: TMZom9Z1dovS87exAC0/mW2l5h7EduXm7kf5oIBCjHwISkavkmltOSnF5TTkqXoGIjwI6rmkAboxxv/4ZyjZG9/yDiXd0x4tYn5hsq7UmvNj+TYdEqfF3ZWpDO8Ffz3UrxqJZ3zhgi8wIPDb4b52+jFgaA8rpcUfKzP9EHTs78GhXeCPjKx5oRY+is6Jeu/vefhbahTUvuJQxM1OXnva33dt4o1fkAlYIei0jVaSl5/sCgV2eEeJXz0y/pJKJIZ914byq48jFl97EzXwVoYHyOzOmVT2wZEee0XVoF19u3n87MbI8EdWhUVrpVVHaNu4mgVZ86yClzMrWCf62S1XQCth1zkHIhvgZse2B+JPNw6ySiaOOY5iHK2L8DvnphHpF08yjFWNKr0owGKd1xTa99u5c0jcZDi15AIP1k8KjIzUFZbp2kK4aUiY9PO630UzglV9O+nSp1Big6hhqn2f5SGJUkps+nZA2EYjJD3RN887jP8Z9fYKsi9ATXFsFyrXAq+RnN51MTqmZruspUujR9XkyzBbERxJGts1x7heEhPOzQFIC4CJdZzvJYOqEK3vE+GyhG6db/lh/fkj0d3tesrEUBfGBBm4k62YYmdtw4diLqvrAtXwNABS3SmU+ZqAC15MqGHRvmf2e+zIQtIDwKrOPs8Zld1yTtUKNgtEhi0=
  app: lit-forest-52364
  on:
    repo: namninja/react-trello-testing
