language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: OfIWptX5bmXPqaWa/gH3znL6ns+UM2+BcA7EaQCRsiP0VMBDBPGErWwaX+wfiMA0xM7XO8jaBDFqhevSYhmwHGyN5ngzeb83n/Tl7H2g2UpEZ06/y3aztLq8GKUQwk/UiS6OrnZb9kq7yonBOO78GRFuxWPj9dJWvYAtdBfZ+7NUmttiO6Qf04l8ne/QFsJdjQHPJyJ0LDYqyO0qalzM/lbJ3BctXV+Vj1ycnsGYRyv+vVLN2g7UnsB864StHJ3CakkLdbocG/sdaJg6bBZn9Ub0mUSUWhKpxuD8tdOdSuwQuNGiekHH3aWZGJrXVjVryNS5a8bg1J9dJ0SLPUB7HbrS7CXJPJNHxusalNYPCfzHphBmLHreDFShj4vCadqgS9TKOZTqsIgjI/t+9Qc5jyfe1XDq8g07/u0qKAWGerUaemNAL/Zrz6e6HtlXlADytxtxqkqc+63wDLFq20ucpUjx+V5cLoZvVGXZvn7cszPhDNHzmwakTjlgrApdy/cFH1sNG1rFm3fxIo8VdI4wMJG0UJNe6FJFrdgtEdY5X/F0Lol/ptAT1zxej+IcjLYQZf7CjxaLmaNF9wOY9myYWj/anNoHpHZsx0+ccU3sA/z/4PYrJfi1LggKE9MOqVmiogy4nqZ+Gz2OJ5SAtT7uI80xWvw3M9lHJXTQFKAyEM8=
  app: lit-forest-52364
  on:
    repo: namninja/react-trello-testing
